title:            Roman Kh on Software development, Machine learning, Big Data and other stuff
description:      Software development, Machine learning, Big Data and other stuff
disqus_shortname: 
reading_time:     true
words_per_minute: 150

url: //roman-kh.github.io

# Owner/author information
owner:
  name:            Roman Kh
  avatar:          avatar.jpg
  bio:             "Did something..."
  email:           roman@libertygrant.co.uk
  twitter:         rhudor     
  facebook:        rhudor
  github:          roman-kh
  stackexchange:   http://stackoverflow.com/users/2370124
  linkedin:        rhudo
  instagram:    
  flickr:         
  tumblr:          roman-kh    
#  google_plus:     https://plus.google.com/105902469420566504130

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-71607684-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Moscow
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
sass:
  sass_dir: _sass
  style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
